# Environment information
n_states: 72
n_actions: 20

# Training parameters
lr: 0.001
gamma: 0.99
eps_max: [0.99, 0.1, 0.05]
eps_min: [0.1, 0.05, 0.01]
eps_steps: [60_000, 60_000, 60_000]
grad_clip: 2.
q_clip: 200
buffer_size: 100_000
batch_size: 128
train_epochs: 5
update_samples: 10

# Training node settings
checkpoint_epochs: 100  # Checkpoint the whole node every 100th iteration
load_checkpoint: False
load_checkpoint_config: False
